
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: First
    displayName: First Stage
    jobs:
      - job: A
        displayName: Job A
        steps:
          - script: echo A
      - job: B
        displayName: Job B
        steps:
          - script: echo B
  - stage: Second
    jobs:
      - job: C
        displayName: Job C
        steps:
          - script: echo C
      - job: D 
        displayName: Job D
        steps:
          - script: echo D
