
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - name: name
    value: sameera
  - name: age
    value: 12

stages:
  - stage: First
    displayName: First Stage
    jobs:
      - job: A
        displayName: Job A
        steps:
          - script: echo $(name)
          - task: PythonScript@0
            inputs:
              scriptSource: 'filePath'
              scriptPath: Src/src.py
      - job: B
        displayName: Job B
        dependsOn: A
        steps:
          - script: echo ${{variables.age}}
  - stage: Second
    jobs:
      - job: C
        displayName: Job C
        steps:
          - script: echo C
      - job: D 
        displayName: Job D
        dependsOn: C
        steps:
          - script: echo D
